
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import "../style/theme.scss"
import "../style/main.scss"
import 'bootstrap/dist/css/bootstrap.min.css';
import { usePathname } from 'next/navigation';
import SideBar from "@/layout/SideBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Grocerry Bazar",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const showSidebar = pathname !== '/';
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {showSidebar && <SideBar/>}
        {children}
      </body>
    </html>
  );
}
